// Regenerate the existing dark colour tokens. Never infer a light palette.
import { readFileSync, writeFileSync } from 'node:fs';
const cssFiles = [
  'globals',
  'exhibits',
  'physics',
  'reader-experience',
  'foundations',
  'gum',
];
const tokens = new Set();
for (const name of cssFiles) {
  for (const match of readFileSync('app/' + name + '.css', 'utf8').matchAll(
    /var\(--tone-([a-f0-9]+)\)/g,
  ))
    tokens.add(match[1]);
}
writeFileSync(
  'app/themes.css',
  '/* Dark-only palette. Generated by scripts/build-theme.mjs. */\n:root {\n  color-scheme: dark;\n' +
    [...tokens]
      .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
      .map((hex) => `  --tone-${hex}: #${hex};`)
      .join('\n') +
    '\n}\n',
);
console.log(`Generated ${tokens.size} dark colour tokens.`);
